Topee/Controllers/favorite_goodsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Topee.Models;

namespace Topee.Controllers
{
    public class favorite_goodsController : Controller
    {
        private TopeeDatabaseEntities db = new TopeeDatabaseEntities();

        [HttpPost]
        public void Add_Like_Goods(int id)
        {
            var username = User.Identity.Name;

            var userid = (from a in db.User
                          where a.username == username
                          select a.id).FirstOrDefault();

            var twice = (from a in db.favorite_goods
                         where a.gid == id && a.uid == userid
                         select a).FirstOrDefault();

            if(twice == null)
            {
                var like = new favorite_goods()
                {
                    gid = id,
                    uid = userid
                };

                db.favorite_goods.Add(like);
                db.SaveChanges();
            }
        }


        // GET: favorite_goods
        [Authorize]
        public ActionResult Index()
        {
            var info = User.Identity.Name;

            var userid = (from a in db.User
                          where a.username == info
                          select a.id).FirstOrDefault();

            var favorite_goods = (from a in db.favorite_goods
                                  where a.uid == userid
                                  select a).ToList();

            //var favorite_goods = db.favorite_goods.Include(f => f.Goods).Include(f => f.User);
            if (favorite_goods.Count() == 0)
            {
                ViewBag.message = "無收藏商品";
            }
            return View(favorite_goods);
        }


        // GET: favorite_goods/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            favorite_goods favorite_goods = db.favorite_goods.Find(id);
            if (favorite_goods == null)
            {
                return HttpNotFound();
            }
            return View(favorite_goods);
        }

        // POST: favorite_goods/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            favorite_goods favorite_goods = db.favorite_goods.Find(id);
            db.favorite_goods.Remove(favorite_goods);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Topee/Controllers/favorite_storeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Security.Cryptography;
using System.Web;
using System.Web.Mvc;
using Topee.Models;

namespace Topee.Controllers
{
    public class favorite_storeController : Controller
    {
        private TopeeDatabaseEntities db = new TopeeDatabaseEntities();

        [HttpPost]
        public void Add_Follow_Store(int id)
        {
            var info = User.Identity.Name;

            var userid = (from a in db.User
                          where a.username == info
                          select a.id).FirstOrDefault();

            var twice = (from a in db.favorite_store
                         where a.sid == id && userid == a.uid
                         select a).FirstOrDefault();

            if(twice == null)
            {
                var follow = new favorite_store()
                {
                    sid = id,
                    uid = userid
                };

                db.favorite_store.Add(follow);
                db.SaveChanges();
            }
        }

        // GET: favorite_store
        [Authorize]
        public ActionResult Index()
        {
            var info = User.Identity.Name;
            var favorite_store = (from a in db.User
                                  from b in db.favorite_store
                                  where a.username == info && b.uid == a.id
                                  select b).ToList();
            if (favorite_store.Count() == 0)
            {
                ViewBag.message = "無追蹤店家";
            }
            return View(favorite_store);
        }

        // GET: favorite_store/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            favorite_store favorite_store = db.favorite_store.Find(id);
            if (favorite_store == null)
            {
                return HttpNotFound();
            }
            return View(favorite_store);
        }

        // POST: favorite_store/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            favorite_store favorite_store = db.favorite_store.Find(id);
            db.favorite_store.Remove(favorite_store);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Topee/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Topee</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>

    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Topee", "Home", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                @{
                    if (Request.IsAuthenticated)
                    {
                        var info = User.Identity.Name;
                        <ul class="nav navbar-nav">
                            <li>@Html.ActionLink("購物車", "Shop_car", "Home")</li>
                            <li>@Html.ActionLink("收藏", "Index", "favorite_goods")</li>
                            <li>@Html.ActionLink("追蹤", "Index", "favorite_store")</li>

                        </ul>
                        <ul class="nav navbar-nav navbar-right">
                            <li>@Html.ActionLink(@info, "Details", "Home")</li>
                            <li>@Html.ActionLink("登出", "Logout", "Home")</li>
                        </ul>

                    }
                    else
                    {
                        <ul class="nav navbar-nav navbar-right">

                            <li>@Html.ActionLink("登入", "Login", "Home")</li>
                            <li>@Html.ActionLink("註冊", "Create", "Home")</li>
                        </ul>
                    }
                }
            </div>

        </div>
    </div>



    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Topee購物網站</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

@{

}